# Generated by Django 4.1.3 on 2022-11-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_figureimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='graph',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FigureImage',
        ),
    ]
