# Generated by Django 4.1.3 on 2022-12-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='point',
            field=models.IntegerField(default=5),
        ),
    ]
